config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :user, :only => [:show, :edit,:update,:index] do
    resources :conversations, :only => [:show, :create] do
      resources :messages, :only => [:create]
    end
  end

  resources :likes, :only => [:create, :destroy]
  resources :posts do
    resources :comments, :only => [:create]
    end
  devise_for :users, controllers: {registrations: "registrations"}

  get 'user/:id/edit' => 'user#edit', as: :'user_edit'
  get 'user_posts/:id' => 'posts#user_posts', as: :'user_posts'

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages
  belongs_to :user
  validates_uniqueness_of :partner_id, :scope => :user_id
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def show
    @messages = @conversation.messages.all
    @message = @conversation.messages.new
  end

  def create
    @conversation = current_user.conversations.new(conversation_params)
    @conversation.save
    user = User.find(id =  params[:conversation][:partner_id])
    params[:conversation][:partner_id], params[:conversation][:user_id]=
        params[:conversation][:user_id],params[:conversation][:partner_id]
    conversation = user.conversations.new(conversation_params)
    conversation.save
    redirect_to(user_conversation_path(current_user, @conversation))
  end

  private
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    def conversation_params
      params.require(:conversation).permit(:user_id, :partner_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= simple_form_for [current_user, conversation] do |f| %>
<div class="field">
  <%= f.hidden_field :partner_id, value: user.id  %>
</div>
<div class="field">
  <%= f.hidden_field :user_id, value: current_user.id  %>
</div>
<%= f.submit "Conversation with #{user.name}" ,class: "btn-link"%>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<h1>Listing conversations</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Second</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.first_id %></td>
        <td><%= conversation.second_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<div class = "messages">
  <table class="m">
    <tbody>
    <% @messages.each do |message|%>
    <tr>
        <td class="message-text">
          <% if (message.sender_id != nil)%>
              <p style="font-weight: bold"><%= link_to User.find(id = message.sender_id).name,
                                                           User.find(id = message.sender_id), class: "btn-link"%></p>
          <%end%>
            <p class="content"><%= message.content %></p>
          <br>
          <br>
          <br>
          <br>
        </td>
        <td class="message-date">
           <p class="message-date"> <%= message.created_at.strftime("%T %F") %></p>
          <br>
          <br>
          <br>
          <br>
        </td>
        </tr>
    <%end%>
    </tbody>
  </table>
</div>
<%= render partial: "messages/form", locals: { message:@message, conversation:@conversation} %>