config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :user, :only => [:show, :edit,:update,:index] do
    resources :conversations, :only => [:show, :create] do
      resources :messages, :only => [:create]
    end
  end

  resources :likes, :only => [:create, :destroy]
  resources :posts do
    resources :comments, :only => [:create]
    end
  devise_for :users, controllers: {registrations: "registrations"}

  get 'user/:id/edit' => 'user#edit', as: :'user_edit'
  get 'user_posts/:id' => 'posts#user_posts', as: :'user_posts'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,]

  def user_posts
    set_user
    @authors = Hash.new
    @posts = Post.where(user_id: @user.id)
    @posts.each do |post|
      if (post.user_id!= nil)
        @user = User.find(id = post.user_id)
        @authors[post.id]= @user.name
      end
    end
  end

  def index
    @authors = Hash.new
    @like = current_user.likes.new
    @posts = Post.all
    @posts.each do |post|
      if (post.user_id!= nil)
        @user = User.find(id = post.user_id)
        @authors[post.id]= @user.name
      end
    end
    respond_to do |format|
	format.html {}
	format.json {render json: @posts}
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.all
    @comment = @post.comments.new
    @authors = Hash.new
    @posts = Post.all
    @posts.each do |post|
      if (post.user_id!= nil)
        @user = User.find(id = post.user_id)
        @authors[post.id]= @user.name
      end
    end
    @authors1 = Hash.new
    @comments = @post.comments.all
    @comments.each do |comment|
      if (comment.post_id!= nil && comment.user_id!= nil)
        @user = User.find(id=comment.user_id)
        @authors1[comment.id]= @user.name
      end
    end
    end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path}
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_comment
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post) }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params[:post][:user_id] = current_user.id
    params.require(:post).permit(:title, :content, :user_id)
  end

  def comment_params
    set_post
    param[:comment][:post_id] = @post.id
    params.require(:comment).permit(:user_name, :content)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post, class: 'btn-link' %> |
<%= link_to 'Back', posts_path, class: 'btn-link' %>

app/views/posts/index.html.erb
<table class="table">
  <tbody>
  <td class="col1"><%= link_to 'All posts', posts_path, class: 'btn-link'%></td>
  <td class="col1"><%= link_to 'My posts', user_posts_path(current_user), class: 'btn-link'%></td>
  <td class="col2"><%= link_to 'New post', new_post_path, class: 'btn-link'%></td>


  </tbody>
</table>

<% @posts.each do |post| %>
    <div class="post">
      <p class="title"><%= link_to post.title, post, class: 'btn-link' %></p>
      <br>

      <p class="content"><%= post.content %></p>
      <br>
      <div class = "like">
        <%= render partial: 'likes/like_button', locals: {post: post}  %>
      </div>
          <p class="author">Posted by <%=link_to @authors[post.id], user_path(User.find(id=post.user_id)),
                                                 class: 'btn-link'%> at <%= post.created_at.strftime("%T %F") %>


    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post">
  <p class = "title"><%= link_to @post.title, @post,  class: 'btn-link'%></p>
  <br>
  <p class = "content"><%=@post.content%></p>
  <br>
  <<div class = "like">
  <%= render partial: 'likes/like_button', locals: {post: @post}  %>
</div>
  <p class="author">Posted by <%=link_to @authors[@post.id], user_path(User.find(id=@post.user_id)),
                                         class: 'btn-link'%> at <%= @post.created_at.strftime("%T %F") %>

</div>

<%if @post.user_id == current_user.id%>
<p style="padding-left: 40%"><%= link_to 'Edit', edit_post_path(@post), class: 'btn-link' %></p>
<%end%>
<br>
<br>
<br>
<br>
<br>
<br>
<h3 class="comments">Comments</h3>
<br>
<br>
<div class="hr">
  </div>
<%@comments.each do |comment|%>
    <%if comment.user_id != nil%>
    <p class="comment-content"><%=comment.content%></p>
    <p class="comment-author"><%=link_to @authors1[comment.id], user_path(User.find(id=comment.user_id)),
                                           class: 'btn-link'%> answered at <%= comment.created_at.strftime("%T %F") %></p>
        <br>
        <br>
<%end%>
<%end%>
<br>
<%= render partial: "comments/form", locals: { post:@post, comment:@comment} %>

app/views/posts/user_posts.html.erb
<table class="table">
  <tbody>
  <td class="col1"><%= link_to 'All posts', posts_path, class: 'btn-link'%></td>
  <td class="col1"><%= link_to 'My posts', user_posts_path(current_user), class: 'btn-link'%></td>
  <td class="col2"><%= link_to 'New post', new_post_path, class: 'btn-link'%></td>
  </tbody>
</table>

<% @posts.each do |post| %>
    <div class="post">
      <p class="title"><%= link_to post.title, post, class: 'btn-link' %></p>
      <br>

      <p class="content"><%= post.content %></p>
      <br>
      <% if post.user_id != nil %>
          <p class="author">Posted by <%=link_to @authors[post.id], user_path(User.find(id=post.user_id)), class: 'btn-link'%> at <%= post.created_at.strftime("%T %F") %></p>
    <% end %>
    </div>
<% end %>